In [ ]:
!CUDA_LAUNCH_BLOCKING=1

In [ ]:
from google.colab import drive
drive.mount('/content/drive/', force_remount=True)

Mounted at /content/drive/


In [ ]:
! ls /content/trial/multilingual

trial.ar-ar.data  trial.en-en.gold  trial.ru-ru.data  trial.zh-zh.gold
trial.ar-ar.gold  trial.fr-fr.data  trial.ru-ru.gold
trial.en-en.data  trial.fr-fr.gold  trial.zh-zh.data


In [ ]:
path_to_data = '/content/drive/My Drive/NLP/trial/'
files_cross = "trial.en-ar.data  trial.en-es.gold  trial.en-ru.data  trial.en-zh.gold  trial.en-ar.gold  trial.en-fr.data  trial.en-ru.gold  trial.en-es.data  trial.en-fr.gold  trial.en-zh.data"
files_cross = files_cross.split('  ')
files_multi = "trial.ar-ar.data  trial.en-en.gold  trial.ru-ru.data  trial.zh-zh.gold  trial.ar-ar.gold  trial.fr-fr.data  trial.ru-ru.gold  trial.en-en.data  trial.fr-fr.gold  trial.zh-zh.data"
files_multi = files_multi.split('  ')


In [ ]:
data = []
results = []
for i in files_cross:
  path = path_to_data + "crosslingual/"+i
  if("gold" in i.split('.')):
    file = open(path,'r').read().split('\n')[:-1]
    for j in file:
      results.append(j.split('\t'))
  else:
    file = open(path,'r').read().split('\n')[:-1]
    for j in file:
      data.append(j.split('\t'))
  
for i in files_multi:
  path = path_to_data + "multilingual/"+i
  if("gold" in i.split('.')):
    file = open(path,'r').read().split('\n')[:-1]
    for j in file:
      results.append(j.split('\t'))
  else:
    file = open(path,'r').read().split('\n')[:-1]
    for j in file:
      data.append(j.split('\t'))

In [ ]:
data[0]

['trial.en-ar.0',
 'report',
 'VERB',
 'en',
 '17',
 'ar',
 '1',
 'Any alterations which it is proposed to make as a result of this review are to be reported to the Interdepartmental Committee on Charter Repertory for its approval .',
 'و  أبلغ  أيضاً  أن  وفاة  "  خوستنيانو  هورتادو  توري  "  ترجع  ،  حسب  التاريخ  اﻻكلينيكي  ،  إلى  المرض .']

In [ ]:
results[0]

In [ ]:
import pandas as pd
data = pd.DataFrame(data)
results = pd.DataFrame(results)


In [ ]:
data.head()

0  ...                                                  8
0  trial.en-ar.0  ...  و  أبلغ  أيضاً  أن  وفاة  "  خوستنيانو  هورتاد...
1  trial.en-ar.1  ...  و  سوف  يرفع  المشاركون  تقارير  عن  الحلقة  ا...
2  trial.en-ar.2  ...  و  أشار  الى  ضرورة  مواصلة  مناقشة  هذه  النق...
3  trial.en-ar.3  ...  إﻻ  أن  ه  لم  يتم  حتى  اﻵن  وضع  أي  مبادئ  ...
4  trial.en-ar.4  ...  و  أشارت  التقارير الواردة  أيضــاً  إلـى  أن ...

[5 rows x 9 columns]

In [ ]:
!nvidia-smi

NVIDIA-SMI has failed because it couldn't communicate with the NVIDIA driver. Make sure that the latest NVIDIA driver is installed and running.



In [ ]:
import torch

# If there's a GPU available...
if torch.cuda.is_available():    

    # Tell PyTorch to use the GPU.    
    device = torch.device("cuda")

    print('There are %d GPU(s) available.' % torch.cuda.device_count())

    print('We will use the GPU:', torch.cuda.get_device_name(0))

# If not...
else:
    print('No GPU available, using the CPU instead.')
    device = torch.device("cpu")

There are 1 GPU(s) available.
We will use the GPU: Tesla P100-PCIE-16GB


In [ ]:
!pip install transformers

     |████████████████████████████████| 1.1MB 4.7MB/s 
     |████████████████████████████████| 890kB 26.0MB/s 
     |████████████████████████████████| 3.0MB 34.1MB/s 
     |████████████████████████████████| 1.1MB 46.0MB/s 
  Created wheel for sacremoses: filename=sacremoses-0.0.43-cp36-none-any.whl size=893257 sha256=c3cb5b2f5c642cc45b8234647af67c77dabce838809733ecb58a19b7f829d302
  Stored in directory: /root/.cache/pip/wheels/29/3c/fd/7ce5c3f0666dab31a50123635e6fb5e19ceb42ce38d4e58f45
Successfully built sacremoses


In [ ]:
from transformers import BertTokenizer

# Load the BERT tokenizer.
print('Loading BERT tokenizer...')
tokenizer = BertTokenizer.from_pretrained('bert-base-uncased', do_lower_case=True)

Loading BERT tokenizer...


In [ ]:
# sentences = data[data.columns[7]] + np.array([' [SEP] ']*data.shape[0]) + data[data.columns[8]]]

# Print the original sentence.
print(' Original: ', sentences[0])

# Print the sentence split into tokens.
print('Tokenized: ', tokenizer.tokenize(sentences[0]))

# Print the sentence mapped to token ids.
print('Token IDs: ', tokenizer.convert_tokens_to_ids(tokenizer.tokenize(sentences[0])))

 Original:  Any alterations which it is proposed to make as a result of this review are to be reported to the Interdepartmental Committee on Charter Repertory for its approval . [SEP] و  أبلغ  أيضاً  أن  وفاة  "  خوستنيانو  هورتادو  توري  "  ترجع  ،  حسب  التاريخ  اﻻكلينيكي  ،  إلى  المرض .
Tokenized:  ['any', 'alterations', 'which', 'it', 'is', 'proposed', 'to', 'make', 'as', 'a', 'result', 'of', 'this', 'review', 'are', 'to', 'be', 'reported', 'to', 'the', 'inter', '##de', '##par', '##tment', '##al', 'committee', 'on', 'charter', 'repertory', 'for', 'its', 'approval', '.', '[SEP]', 'و', 'ا', '##ب', '##ل', '##غ', 'ا', '##ي', '##ض', '##ا', 'ا', '##ن', 'و', '##ف', '##ا', '##ة', '"', 'خ', '##و', '##س', '##ت', '##ن', '##ي', '##ان', '##و', 'ه', '##و', '##ر', '##ت', '##ا', '##د', '##و', 'ت', '##و', '##ر', '##ي', '"', 'ت', '##ر', '##ج', '##ع', '،', 'ح', '##س', '##ب', 'ا', '##ل', '##ت', '##ا', '##ر', '##ي', '##خ', '[UNK]', '،', 'ا', '##ل', '##ى', 'ا', '##ل', '##م', '##ر', '##ض', '.']
Token ID

In [ ]:
sentences =  ((data[7][:] + ' [SEP] ' ) + data[8][:])

In [ ]:
results = results[1].replace('T',2)
results = results.replace('F',1)
results = results.replace('R',0)

In [ ]:
results = results+1

In [ ]:
results

0      2
1      2
2      2
3      2
4      2
      ..
195    2
196    2
197    0
198    2
199    2
Name: 1, Length: 200, dtype: int64

In [ ]:
max_len = 0

# For every sentence...
for sent in sentences:

    # Tokenize the text and add `[CLS]` and `[SEP]` tokens.
    input_ids = tokenizer.encode(sent, add_special_tokens=True)

    # Update the maximum sentence length.
    max_len = max(max_len, len(input_ids))

print('Max sentence length: ', max_len)

Max sentence length:  470


In [ ]:
# Tokenize all of the sentences and map the tokens to thier word IDs.
import torch
input_ids = []
attention_masks = []

# For every sentence...
for sent in sentences:
    # `encode_plus` will:
    #   (1) Tokenize the sentence.
    #   (2) Prepend the `[CLS]` token to the start.
    #   (3) Append the `[SEP]` token to the end.
    #   (4) Map tokens to their IDs.
    #   (5) Pad or truncate the sentence to `max_length`
    #   (6) Create attention masks for [PAD] tokens.
    encoded_dict = tokenizer.encode_plus(
                        sent,                      # Sentence to encode.
                        add_special_tokens = True,
                        truncation=True, # Add '[CLS]' and '[SEP]'
                        max_length = 500,           # Pad & truncate all sentences.
                        pad_to_max_length = True,
                        return_attention_mask = True,   # Construct attn. masks.
                        return_tensors = 'pt',     # Return pytorch tensors.
                   )
    
    # Add the encoded sentence to the list.    
    input_ids.append(encoded_dict['input_ids'])
    
    # And its attention mask (simply differentiates padding from non-padding).
    attention_masks.append(encoded_dict['attention_mask'])

# Convert the lists into tensors.
input_ids = torch.cat(input_ids, dim=0)
attention_masks = torch.cat(attention_masks, dim=0)
labels = torch.tensor(results)

# Print sentence 0, now as a list of IDs.
print('Original: ', sentences[0])
print('Token IDs:', input_ids[0])

Original:  Any alterations which it is proposed to make as a result of this review are to be reported to the Interdepartmental Committee on Charter Repertory for its approval . [SEP] و  أبلغ  أيضاً  أن  وفاة  "  خوستنيانو  هورتادو  توري  "  ترجع  ،  حسب  التاريخ  اﻻكلينيكي  ،  إلى  المرض .
Token IDs: tensor([  101,  2151, 16705,  2029,  2009,  2003,  3818,  2000,  2191,  2004,
         1037,  2765,  1997,  2023,  3319,  2024,  2000,  2022,  2988,  2000,
         1996,  6970,  3207, 19362, 21181,  2389,  2837,  2006,  6111, 21099,
         2005,  2049,  6226,  1012,   102,  1298,  1270, 29816, 23673, 29831,
         1270, 14498, 29827, 25573,  1270, 15915,  1298, 29833, 25573, 19433,
         1000,  1277, 29836, 29824, 29817, 15915, 14498, 18511, 29836,  1297,
        29836, 17149, 29817, 25573, 15394, 29836,  1273, 29836, 17149, 14498,
         1000,  1273, 17149, 29819, 29830,  1268,  1276, 29824, 29816,  1270,
        23673, 29817, 25573, 17149, 14498, 29821,   100,  1268,  1270, 236

/usr/local/lib/python3.6/dist-packages/transformers/tokenization_utils_base.py:1773: FutureWarning: The `pad_to_max_length` argument is deprecated and will be removed in a future version, use `padding=True` or `padding='longest'` to pad to the longest sequence in the batch, or use `padding='max_length'` to pad to a max length. In this case, you can give a specific length with `max_length` (e.g. `max_length=45`) or leave max_length to None to pad to the maximal input size of the model (e.g. 512 for Bert).
  FutureWarning,


In [ ]:
from torch.utils.data import TensorDataset, random_split

# Combine the training inputs into a TensorDataset.
dataset = TensorDataset(input_ids, attention_masks, labels)

# Create a 90-10 train-validation split.

# Calculate the number of samples to include in each set.
train_size = int(0.9 * len(dataset))
val_size = len(dataset) - train_size

# Divide the dataset by randomly selecting samples.
train_dataset, val_dataset = random_split(dataset, [train_size, val_size])

print('{:>5,} training samples'.format(train_size))
print('{:>5,} validation samples'.format(val_size))

  180 training samples
   20 validation samples


In [ ]:
from torch.utils.data import DataLoader, RandomSampler, SequentialSampler

# The DataLoader needs to know our batch size for training, so we specify it 
# here. For fine-tuning BERT on a specific task, the authors recommend a batch 
# size of 16 or 32.
batch_size = 2

# Create the DataLoaders for our training and validation sets.
# We'll take training samples in random order. 
train_dataloader = DataLoader(
            train_dataset,  # The training samples.
            sampler = RandomSampler(train_dataset), # Select batches randomly
            batch_size = batch_size # Trains with this batch size.
        )

# For validation the order doesn't matter, so we'll just read them sequentially.
validation_dataloader = DataLoader(
            val_dataset, # The validation samples.
            sampler = SequentialSampler(val_dataset), # Pull out batches sequentially.
            batch_size = batch_size # Evaluate with this batch size.
        )

In [ ]:
from transformers import BertForSequenceClassification, AdamW, BertConfig

# Load BertForSequenceClassification, the pretrained BERT model with a single 
# linear classification layer on top. 
model = BertForSequenceClassification.from_pretrained(
    "bert-base-multilingual-uncased", # Use the 12-layer BERT model, with an uncased vocab.
    num_labels = 3, # The number of output labels--2 for binary classification.
                    # You can increase this for multi-class tasks.   
    output_attentions = False, # Whether the model returns attentions weights.
    output_hidden_states = False, # Whether the model returns all hidden-states.
)

# Tell pytorch to run this model on the GPU.
# model.cuda()

Some weights of the model checkpoint at bert-base-multilingual-uncased were not used when initializing BertForSequenceClassification: ['cls.predictions.bias', 'cls.predictions.transform.dense.weight', 'cls.predictions.transform.dense.bias', 'cls.predictions.decoder.weight', 'cls.seq_relationship.weight', 'cls.seq_relationship.bias', 'cls.predictions.transform.LayerNorm.weight', 'cls.predictions.transform.LayerNorm.bias']
- This IS expected if you are initializing BertForSequenceClassification from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPretraining model).
- This IS NOT expected if you are initializing BertForSequenceClassification from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).
Some weights of BertForSequenceClassification were not initialized from the model 

In [ ]:
# Get all of the model's parameters as a list of tuples.
params = list(model.named_parameters())

print('The BERT model has {:} different named parameters.\n'.format(len(params)))

print('==== Embedding Layer ====\n')

for p in params[0:5]:
    print("{:<55} {:>12}".format(p[0], str(tuple(p[1].size()))))

print('\n==== First Transformer ====\n')

for p in params[5:21]:
    print("{:<55} {:>12}".format(p[0], str(tuple(p[1].size()))))

print('\n==== Output Layer ====\n')

for p in params[-4:]:
    print("{:<55} {:>12}".format(p[0], str(tuple(p[1].size()))))

The BERT model has 201 different named parameters.

==== Embedding Layer ====

bert.embeddings.word_embeddings.weight                  (105879, 768)
bert.embeddings.position_embeddings.weight                (512, 768)
bert.embeddings.token_type_embeddings.weight                (2, 768)
bert.embeddings.LayerNorm.weight                              (768,)
bert.embeddings.LayerNorm.bias                                (768,)

==== First Transformer ====

bert.encoder.layer.0.attention.self.query.weight          (768, 768)
bert.encoder.layer.0.attention.self.query.bias                (768,)
bert.encoder.layer.0.attention.self.key.weight            (768, 768)
bert.encoder.layer.0.attention.self.key.bias                  (768,)
bert.encoder.layer.0.attention.self.value.weight          (768, 768)
bert.encoder.layer.0.attention.self.value.bias                (768,)
bert.encoder.layer.0.attention.output.dense.weight        (768, 768)
bert.encoder.layer.0.attention.output.dense.bias              

In [ ]:
# Note: AdamW is a class from the huggingface library (as opposed to pytorch) 
# I believe the 'W' stands for 'Weight Decay fix"
optimizer = AdamW(model.parameters(),
                  lr = 2e-5, # args.learning_rate - default is 5e-5, our notebook had 2e-5
                  eps = 1e-8 # args.adam_epsilon  - default is 1e-8.
                )


In [ ]:
from transformers import get_linear_schedule_with_warmup

# Number of training epochs. The BERT authors recommend between 2 and 4. 
# We chose to run for 4, but we'll see later that this may be over-fitting the
# training data.
epochs = 4

# Total number of training steps is [number of batches] x [number of epochs]. 
# (Note that this is not the same as the number of training samples).
total_steps = len(train_dataloader) * epochs

# Create the learning rate scheduler.
scheduler = get_linear_schedule_with_warmup(optimizer, 
                                            num_warmup_steps = 0, # Default value in run_glue.py
                                            num_training_steps = total_steps)

In [ ]:
import numpy as np

# Function to calculate the accuracy of our predictions vs labels
def flat_accuracy(preds, labels):
    pred_flat = np.argmax(preds, axis=1).flatten()
    labels_flat = labels.flatten()
    return np.sum(pred_flat == labels_flat) / len(labels_flat)

In [ ]:
import time
import datetime

def format_time(elapsed):
    '''
    Takes a time in seconds and returns a string hh:mm:ss
    '''
    # Round to the nearest second.
    elapsed_rounded = int(round((elapsed)))
    
    # Format as hh:mm:ss
    return str(datetime.timedelta(seconds=elapsed_rounded))

In [ ]:
import random
import numpy as np

# This training code is based on the `run_glue.py` script here:
# https://github.com/huggingface/transformers/blob/5bfcd0485ece086ebcbed2d008813037968a9e58/examples/run_glue.py#L128

# Set the seed value all over the place to make this reproducible.
seed_val = 42

random.seed(seed_val)
np.random.seed(seed_val)
torch.manual_seed(seed_val)
# torch.cuda.manual_seed_all(seed_val)

# We'll store a number of quantities such as training and validation loss, 
# validation accuracy, and timings.
training_stats = []

# Measure the total training time for the whole run.
total_t0 = time.time()

# For each epoch...
for epoch_i in range(0, epochs):
    
    # ========================================
    #               Training
    # ========================================
    
    # Perform one full pass over the training set.

    print("")
    print('======== Epoch {:} / {:} ========'.format(epoch_i + 1, epochs))
    print('Training...')

    # Measure how long the training epoch takes.
    t0 = time.time()

    # Reset the total loss for this epoch.
    total_train_loss = 0

    # Put the model into training mode. Don't be mislead--the call to 
    # `train` just changes the *mode*, it doesn't *perform* the training.
    # `dropout` and `batchnorm` layers behave differently during training
    # vs. test (source: https://stackoverflow.com/questions/51433378/what-does-model-train-do-in-pytorch)
    model.train()

    # For each batch of training data...
    for step, batch in enumerate(train_dataloader):

        # Progress update every 40 batches.
        if step % 40 == 0 and not step == 0:
            # Calculate elapsed time in minutes.
            elapsed = format_time(time.time() - t0)
            
            # Report progress.
            print('  Batch {:>5,}  of  {:>5,}.    Elapsed: {:}.'.format(step, len(train_dataloader), elapsed))

        # Unpack this training batch from our dataloader. 
        #
        # As we unpack the batch, we'll also copy each tensor to the GPU using the 
        # `to` method.
        #
        # `batch` contains three pytorch tensors:
        #   [0]: input ids 
        #   [1]: attention masks
        #   [2]: labels 
        print('here - ',batch[0].get_device())
        # print(device)
        # print(type(batch))
        # print(type(batch[0]))
        p_batch = batch[0]
        b_input_ids = p_batch
        b_input_mask = batch[1]
        b_labels = batch[2]

        # Always clear any previously calculated gradients before performing a
        # backward pass. PyTorch doesn't do this automatically because 
        # accumulating the gradients is "convenient while training RNNs". 
        # (source: https://stackoverflow.com/questions/48001598/why-do-we-need-to-call-zero-grad-in-pytorch)
        model.zero_grad()        

        # Perform a forward pass (evaluate the model on this training batch).
        # The documentation for this `model` function is here: 
        # https://huggingface.co/transformers/v2.2.0/model_doc/bert.html#transformers.BertForSequenceClassification
        # It returns different numbers of parameters depending on what arguments
        # arge given and what flags are set. For our useage here, it returns
        # the loss (because we provided labels) and the "logits"--the model
        # outputs prior to activation.
        print(b_labels)
        loss, logits = model(b_input_ids, 
                             token_type_ids=None, 
                             attention_mask=b_input_mask, 
                             labels=b_labels)

        # Accumulate the training loss over all of the batches so that we can
        # calculate the average loss at the end. `loss` is a Tensor containing a
        # single value; the `.item()` function just returns the Python value 
        # from the tensor.
        
        # print(loss)
        total_train_loss += loss.item()

        # Perform a backward pass to calculate the gradients.
        loss.backward()

        # Clip the norm of the gradients to 1.0.
        # This is to help prevent the "exploding gradients" problem.
        torch.nn.utils.clip_grad_norm_(model.parameters(), 1.0)

        # Update parameters and take a step using the computed gradient.
        # The optimizer dictates the "update rule"--how the parameters are
        # modified based on their gradients, the learning rate, etc.
        optimizer.step()

        # Update the learning rate.
        scheduler.step()

    # Calculate the average loss over all of the batches.
    avg_train_loss = total_train_loss / len(train_dataloader)            
    
    # Measure how long this epoch took.
    training_time = format_time(time.time() - t0)

    print("")
    print("  Average training loss: {0:.2f}".format(avg_train_loss))
    print("  Training epcoh took: {:}".format(training_time))
        
    # ========================================
    #               Validation
    # ========================================
    # After the completion of each training epoch, measure our performance on
    # our validation set.

    print("")
    print("Running Validation...")

    t0 = time.time()

    # Put the model in evaluation mode--the dropout layers behave differently
    # during evaluation.
    model.eval()

    # Tracking variables 
    total_eval_accuracy = 0
    total_eval_loss = 0
    nb_eval_steps = 0

    # Evaluate data for one epoch
    for batch in validation_dataloader:
        
        # Unpack this training batch from our dataloader. 
        #
        # As we unpack the batch, we'll also copy each tensor to the GPU using 
        # the `to` method.
        #
        # `batch` contains three pytorch tensors:
        #   [0]: input ids 
        #   [1]: attention masks
        #   [2]: labels 
        b_input_ids = batch[0]
        b_input_mask = batch[1]
        b_labels = batch[2]
        
        # Tell pytorch not to bother with constructing the compute graph during
        # the forward pass, since this is only needed for backprop (training).
        with torch.no_grad():        

            # Forward pass, calculate logit predictions.
            # token_type_ids is the same as the "segment ids", which 
            # differentiates sentence 1 and 2 in 2-sentence tasks.
            # The documentation for this `model` function is here: 
            # https://huggingface.co/transformers/v2.2.0/model_doc/bert.html#transformers.BertForSequenceClassification
            # Get the "logits" output by the model. The "logits" are the output
            # values prior to applying an activation function like the softmax.
            (loss, logits) = model(b_input_ids, 
                                   token_type_ids=None, 
                                   attention_mask=b_input_mask,
                                   labels=b_labels)
            
        # Accumulate the validation loss.
        total_eval_loss += loss.item()

        # Move logits and labels to CPU
        logits = logits.detach().numpy()
        label_ids = b_labels.numpy()

        # Calculate the accuracy for this batch of test sentences, and
        # accumulate it over all batches.
        total_eval_accuracy += flat_accuracy(logits, label_ids)
        

    # Report the final accuracy for this validation run.
    avg_val_accuracy = total_eval_accuracy / len(validation_dataloader)
    print("  Accuracy: {0:.2f}".format(avg_val_accuracy))

    # Calculate the average loss over all of the batches.
    avg_val_loss = total_eval_loss / len(validation_dataloader)
    
    # Measure how long the validation run took.
    validation_time = format_time(time.time() - t0)
    
    print("  Validation Loss: {0:.2f}".format(avg_val_loss))
    print("  Validation took: {:}".format(validation_time))

    # Record all statistics from this epoch.
    training_stats.append(
        {
            'epoch': epoch_i + 1,
            'Training Loss': avg_train_loss,
            'Valid. Loss': avg_val_loss,
            'Valid. Accur.': avg_val_accuracy,
            'Training Time': training_time,
            'Validation Time': validation_time
        }
    )

print("")
print("Training complete!")

print("Total training took {:} (h:mm:ss)".format(format_time(time.time()-total_t0)))


======== Epoch 1 / 4 ========
Training...
here -  -1
tensor([2, 2])
here -  -1
tensor([2, 2])
here -  -1
tensor([2, 2])
here -  -1
tensor([0, 2])
here -  -1
tensor([2, 0])
here -  -1
tensor([1, 2])
here -  -1
tensor([0, 2])
here -  -1
tensor([2, 1])
here -  -1
tensor([2, 2])
here -  -1
tensor([2, 0])
here -  -1
tensor([2, 2])
here -  -1
tensor([2, 0])
here -  -1
tensor([2, 0])
here -  -1
tensor([2, 2])
here -  -1
tensor([2, 2])
here -  -1
tensor([2, 2])
here -  -1
tensor([1, 1])
here -  -1
tensor([2, 2])
here -  -1
tensor([2, 1])
here -  -1
tensor([2, 0])
here -  -1
tensor([1, 2])
here -  -1
tensor([2, 2])
here -  -1
tensor([2, 2])
here -  -1
tensor([0, 2])
here -  -1
tensor([1, 2])
here -  -1
tensor([2, 0])
here -  -1
tensor([2, 2])
here -  -1
tensor([0, 2])
here -  -1
tensor([0, 2])
here -  -1
tensor([2, 0])
here -  -1
tensor([0, 1])
here -  -1
tensor([0, 2])
here -  -1
tensor([0, 2])
here -  -1
tensor([2, 0])
here -  -1
tensor([2, 0])
here -  -1
tensor([2, 2])
here -  -1
tensor([2,

In [ ]:
type(device)

torch.device

In [ ]:
labels

tensor([ 1,  1,  1,  1,  1,  1,  1,  1,  1,  1, -1,  1, -1, -1,  0, -1,  1,  1,
        -1,  1,  1, -1,  1,  1, -1,  0,  1,  1,  1,  1, -1,  1, -1, -1, -1, -1,
        -1,  1, -1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1, -1,  0, -1, -1,
         0, -1,  1,  1, -1,  1,  1,  1,  1,  1, -1,  1,  1,  1,  1,  1, -1,  1,
         1, -1, -1, -1,  1,  1,  1, -1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
         1,  1, -1, -1,  0, -1,  1,  1, -1,  1,  0,  1, -1, -1,  1,  1, -1,  1,
         0,  1, -1,  1,  1, -1,  0,  1,  1,  1, -1,  1, -1, -1,  1,  1,  1,  1,
         0,  0,  0,  0,  0,  0, -1, -1,  1,  1,  1,  1,  0,  0,  1,  1,  1,  1,
        -1, -1,  1,  1,  1,  1,  0,  0,  1,  1,  1,  1,  1,  1, -1, -1,  1,  1,
         1,  1,  1,  1,  0,  0,  1,  0,  1,  1,  1,  1,  1,  1,  0,  1,  1,  1,
         1,  1,  1, -1,  1,  0,  1,  1,  1,  1,  0, -1,  0,  0,  1,  1,  1, -1,
         1,  1])